### rest api 테스트
### vsc에 REST Client 플러그인을 확장하여 사용
### 포스트맨과 같은 api 테스트 툴 없이도 손쉽게 검증 가능

### Spring actuator Health check 엔드포인트 헬스 체크
GET http://localhost:8080/health

### Spring actuator env로 서비스 정보 조회
GET http://localhost:8080/actuator

### POST 라이센스 등록
PUT  http://localhost:8080/v1/organization/3/license
Content-Type: application/json

{
  "licenseId" : "21123113",
  "organizationId" : "3",
  "description" : "just joke",
  "productName" : "husQuiz",
  "licenseType" : "complete"
}

### GET 라이센스 조회
GET  http://localhost:8080/v1/organization/3/license/21123113

### PUT 라이센스 수정
PUT  http://localhost:8080/v1/organization/3/license
Content-Type: application/json

{
  "licenseId" : "21123113",
  "organizationId" : "3",
  "description" : "update is done",
  "productName" : "husQuiz",
  "licenseType" : "complete"
}

### GET 라이센스 조회
GET  http://localhost:8080/v1/organization/3/license/21123113

### DELETE 라이센스 삭제
DELETE  http://localhost:8080/v1/organization/3/license/21123113

### GET 라이센스 조회
GET  http://localhost:8080/v1/organization/3/license/21123113

